spring:
  data:
    redis:
      client-type: lettuce
      host: 127.0.0.1
      password: 123456
      database: 0
      port: 63790
      timeout: 2000
      lettuce:
        pool:
          enabled: true
          max-active: 8
          min-idle: 0
          max-idle: 8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cgh1?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

log:
  level:
    - name: cn.com.cgh.login
      level: info
    - name: cn.com.cgh.auth
      level: info

springdoc:
  paths-to-exclude:
    - /api/test/**
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  #  use-management-port: false
  api-docs:
    path: /v3/api-docs
    version: openapi_3_1
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.com.cgh
  default-flat-param-object: false

knife4j:
  enable: true
  setting:
    language: zh-CN